### PR TITLE
Proposal to make this role a little more flexible

### PR DESCRIPTION
**Pull request by zonArt**
by adding variables in sonar.properties template and filling up missing parts in dependencies.yml

### CODE REVIEW

**Comment by zonArt** [comment]
@bbaassssiiee What do you think about this PR, do you think you'll merge it one day ? What can I do (apart from solving the conflicts) to get it merge, something missing, not following the role's philosophy ?

**Review by bbaassssiiee — APPROVED** [review]
Looks excellent! Thanks for the improvements.

**Comment by zonArt** [comment]
@bbaassssiiee Conflicts solved, feel free to merge if ok for you

**Comment by bbaassssiiee** [comment]
Thanks for your contribution!

**Comment by zonArt** [comment]
You're welcome

**Pull request merged**
